from enum import Enum


class Event(Enum):
    START = 1
    NOMINATION = 2
    VOTES = 3
    MESSAGE = 4
    ENACTED = 5
    ELECTION_FAIL = 6
    PRESIDENT_CLAIM = 7
    CHANCELLOR_CLAIM = 8
    INVESTIGATION_MESSAGE = 9
    INVESTIGATION_ACTION = 10
    INVESTIGATION_CLAIM = 11
    DECK_SHUFFLE = 12
    SPECIAL_ELECT_MESSAGE = 13
    SPECIAL_ELECT_ACTION = 14
    CHAOS_POLICY = 15
    CHANCELLOR_VETO = 16
    PRESIDENT_VETO = 17
    PEEK_MESSAGE = 18
    PEEK_CLAIM = 19
    EXECUTE_MESSAGE = 20
    EXECUTE_ACTION = 21
    FASCIST_WIN = 22
    LIBERAL_WIN = 23
    DRAW = 24
    DISCARD = 25
    PEEK = 26
    GET_CARD = 27
    INVESTIGATION_RESULT = 28
    PLAY_CARD = 29
    PERSONAL_ROLE_CALL = 30
    ALL_ROLE_CALLS = 31
    PERSONAL_VOTE = 32
