from enum import Enum


class Event(str, Enum):
    START = "START"
    NOMINATION = "NOMINATION"
    VOTES = "VOTES"
    MESSAGE = "MESSAGE"
    ENACTED = "ENACTED"
    ELECTION_FAIL = "ELECTION_FAIL"
    PRESIDENT_CLAIM = "PRESIDENT_CLAIM"
    CHANCELLOR_CLAIM = "CHANCELLOR_CLAIM"
    INVESTIGATION_MESSAGE = "INVESTIGATION_MESSAGE"
    INVESTIGATION_ACTION = "INVESTIGATION_ACTION"
    INVESTIGATION_CLAIM = "INVESTIGATION_CLAIM"
    DECK_SHUFFLE = "DECK_SHUFFLE"
    SPECIAL_ELECT_MESSAGE = "SPECIAL_ELECT_MESSAGE"
    SPECIAL_ELECT_ACTION = "SPECIAL_ELECT_ACTION"
    CHAOS_POLICY = "CHAOS_POLICY"
    CHANCELLOR_VETO = "CHANCELLOR_VETO"
    PRESIDENT_VETO = "PRESIDENT_VETO"
    PEEK_MESSAGE = "PEEK_MESSAGE"
    PEEK_PERSONAL = "PEEK_PERSONAL"
    PEEK_CLAIM = "PEEK_CLAIM"
    EXECUTE_MESSAGE = "EXECUTE_MESSAGE"
    EXECUTE_ACTION = "EXECUTE_ACTION"
    FASCIST_WIN = "FASCIST_WIN"
    LIBERAL_WIN = "LIBERAL_WIN"
    DRAW = "DRAW"
    DISCARD = "DISCARD"
    GET_CARD = "GET_CARD"
    INVESTIGATION_RESULT = "INVESTIGATION_RESULT"
    PLAY_CARD = "PLAY_CARD"
    PERSONAL_ROLE_CALL = "PERSONAL_ROLE_CALL"
    ALL_ROLE_CALLS = "ALL_ROLE_CALLS"
    PERSONAL_VOTE = "PERSONAL_VOTE"
    GAME_SETTINGS = "GAME_SETTINGS"
    NOOP = "NOOP"


PRESIDENT_POWERS = [
    Event.INVESTIGATION_ACTION,
    Event.SPECIAL_ELECT_ACTION,
    Event.EXECUTE_ACTION,
]
